apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: csi-driver-nfs
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://your.git.repo/your-git-repo.git
        revision: HEAD
        directories:
          - path: nfs-csi
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
        chart: nfs-subdir-external-provisioner
        targetRevision: 4.0.18  # Ajusta según versión deseada
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
