apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: csi-driver-nfs
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-csi-driver-nfs'
    spec:
      project: default
      source:
        repoURL: https://github.com/edominguezl/csi-driver-nfs.git
        targetRevision: HEAD
        path: csi-driver-nfs/charts/
        helm:
          valueFiles:
            - values.yaml
      destination:
        namespace: kube-system
        server: '{{url}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
