apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: csi-driver-nfs
spec:
  generators:
    - git:
        repoURL: https://github.com/edominguezl/csi-driver-nfs.git
        revision: HEAD
        directories:
          - path: csi-driver-nfs
  template:
    metadata:
      name: in-cluster-csi-driver-nfs
    spec:
      project: default
      source:
        repoURL: https://github.com/edominguezl/csi-driver-nfs.git
        targetRevision: HEAD
        path: csi-driver-nfs
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
