apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: csi-driver-nfs
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: csi-driver-nfs
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
        chart: csi-driver-nfs
        targetRevision: 4.9.0  # ← ajusta según la versión deseada
        helm:
          valueFiles:
            - csi-driver-nfs/values.yaml  # ← si lo tienes en Git (usa Git generator), o usa "values" inline
      destination:
        server: https://kubernetes.default.svc
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
