apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: csi-driver-nfs
spec:
  generators:
    - git:
        repoURL: https://github.com/edominguezl/csi-driver-nfs.git
        revision: HEAD
        directories:
          - path: csi-driver-nfs/charts
    - clusters:
        selector:
          matchLabels:
            deploy-csi-driver: "true"
  template:
    metadata:
      name: '{{name}}-csi-driver-nfs'
    spec:
      project: default
      source:
        repoURL: https://github.com/edominguezl/csi-driver-nfs.git
        targetRevision: HEAD
        path: csi-driver-nfs/charts
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: '{{server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
