image:
    livenessProbe:
        repository: registry.k8s.io/sig-storage/livenessprobe
        tag: v2.13.1
        pullPolicy: IfNotPresent
csi-driver-nfs:
  kubeletDir: /var/snap/microk8s/common/var/lib/kubelet
  image: v4.9.0

storageClass:
  parameters:
    server: 192.168.64.6
    share: /srv/nfs/shared
  name: nfs-csi
  default: true